### PR TITLE
Command to disable an eslint rule

### PR DESCRIPTION
**Pull request by DamienCassou**
I plan to support all ways to [disable rules in eslint](https://eslint.org/docs/user-guide/configuring/rules#disabling-rules). Would you be interested?

/CC @orzechowskid

### CODE REVIEW

**Comment by orzechowskid** [comment]
I think an interactive function to add `/* eslint-ignore */` comments is a very useful idea.  but the only code here specific to Flymake is the source of the diagnostics, and those diagnostics are emitted by eslint.

do you think this feature would also be useful to anyone using Flycheck's javascript-eslint and typescript-tslint interfaces, for instance?  is it better as a separate minor-mode or part of an existing major-mode?  (or maybe the answer to that is "no", and this is the best place for it?)

**Comment by DamienCassou** [comment]
I think that is an excellent idea. I've just created [https://github.com/DamienCassou/eslint-disable-rule](eslint-disable-rule). 

The package will work with flymake-eslint if:

- you add the `:rule-name` to the diagnostic data as my PR suggests, or if
- `flymake-eslint-show-rule-name` is non-nil in which case a regexp will be used.

I think it makes sense to merge the part of my PR adding `(list :rule-name lint-rule)` so people deactivating `flymake-eslint-show-rule-name` will still be able to use `flymake-eslint`.

What do you think?

Do you want to be my first user? Any feedback?

**Comment by orzechowskid** [comment]
> I think it makes sense to merge the part of my PR adding (list :rule-name lint-rule) so people deactivating flymake-eslint-show-rule-name will still be able to use flymake-eslint.

I agree!  at your convenience, please reduce the scope of this PR (and add yourself to the list of Contributors at the top of the file if you wish), and I would be happy to merge.

> Do you want to be my first user? Any feedback?

at my job I work on a codebase with `eslint-comments/require-description` enabled.  it might be nice to have a `eslint-disable-rule-with-comment` or something which prompts for a description and appends it (along with the `--` delimiter) to the inserted comment.  maybe I will open a PR against your library :)

**Comment by DamienCassou** [comment]
> please reduce the scope of this PR

done

> add yourself to the list of Contributors

I haven't done that as I think the PR is too small to deserve that. Maybe next time :-).

Thank you for your feedback. I have work to do to support flycheck and other disable comments so feel free to contribute with a PR.

**Comment by orzechowskid** [comment]
thanks for contributing!

**Comment by DamienCassou** [comment]
> at my job I work on a codebase with [eslint-comments/require-description](https://mysticatea.github.io/eslint-plugin-eslint-comments/rules/require-description.html) enabled. it might be nice to have a eslint-disable-rule-with-comment or something which prompts for a description and appends it (along with the -- delimiter) to the inserted comment. maybe I will open a PR against your library :)

I've added this feature now and others. Feel free to give feedback: https://github.com/DamienCassou/eslint-disable-rule.

**Pull request merged**
