### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by xFA25E**

### CODE REVIEW

**Comment by orzechowskid** [comment]
thank you for the PR.  it looks like you're doing more than just "cleanup" here.  I can follow the docstring changes and the re-organization of the code could you briefly describe some of the code changes you made?

thanks!

**Comment by orzechowskid** [comment]
this is not a criticism :)  this was maybe the first elisp code I ever published, and I'm sure it can be improved!

**Comment by xFA25E** [comment]
Sure, no problems! There are a lot of changes XD

1. I use alphapapa's [template](https://alphapapa.github.io/emacs-package-dev-handbook/#Template) to organize code. It uses elisp comment headers to leverage `outline-minor-mode`.

2. I modified a docstrings to follow the emacs convention that requires them to be no longer than 80 characters. I also removed parts like _internal function_, since we are using package infixes (`--` and `-`) to distinguish between private and public functions.

3. I've rewritten `message-regexp` with `rx` macro since it is much more maintainable. Also, Emacs uses *regexP* instead of *regex* in symbol names by convention.

4. In the `report` function I used a `cl-loop` instead of a `while` loop to remove the manual collection of diagnostics to result. It is just a preference of mine, if you are against `cl-loop` I can remove it.

5. Other changes are there to make the lines no longer than 80 characters.

**Comment by orzechowskid** [comment]
great, thank you for the PR and the explanation!

**Pull request merged**
